#!/usr/bin/env bash

# Script that configures Nginx server with a custom header

# Update and install Nginx
apt-get -y update
apt-get -y install nginx

# Create default content and custom 404 page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Add custom rules to Nginx configuration
sed -i "
    s/server_name _;/server_name _;\n\trewrite ^\/redirect_me  http:\/\/cuberule.com\/ permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/
" /etc/nginx/sites-available/default

sed -i "
    s|include /etc/nginx/sites-enabled/*;|include /etc/nginx/sites-enabled/*;\n    add_header X-Served-By \"$HOSTNAME\";|;
" /etc/nginx/nginx.conf

# Start Nginx service
service nginx start
