#!/usr/bin/env bash
# Script to configure Nginx server with a custom header

# Update package list
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create default page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx
sed -i "s/server_name _;/\
    server_name _;\n\
    rewrite ^\/redirect_me https:\/\/github.com\/mugambi12 permanent;\n\
    error_page 404 \/custom_404.html;\n\
    location = \/custom_404.html {\n\
        root \/usr\/share\/nginx\/html;\n\
        internal;\n\
    }/" /etc/nginx/sites-available/default

# Add custom header
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/\
    include \/etc\/nginx\/sites-enabled\/\*;\n\
    add_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Start Nginx
service nginx start
