#!/usr/bin/env bash
#!/bin/bash
# This script transfers a file from the local client to a remote server using SCP.
# It accepts four arguments:
#   1. The path to the file to be transferred.
#   2. The IP address of the destination server.
#   3. The username used for SCP connection.
#   4. The path to the SSH private key for authentication.

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Using SCP to transfer the file securely to the remote server.
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
