#!/usr/bin/env bash
# Configuration script for lb-01 server

# Update package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy to send traffic to web-01 and web-02 using roundrobin algorithm
sudo sh -c 'echo '\''frontend sm12se.tech
    bind 0:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 91903-web-01 54.197.105.254:80 check
    server 91903-web-02 100.24.206.145:80 check'\'' >> /etc/haproxy/haproxy.cfg'

# Restart HAProxy service
sudo service haproxy restart
