#!/usr/bin/env bash
# This script attempts to fix Nginx not listening on port 80
[ -e /etc/nginx/sites-enabled/default ] || ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
