#!/usr/bin/env bash
# show_your_bash_processes.sh
# Description: Displays a list of currently running processes containing the "bash" keyword.
#              Uses the 'ps' command to list all processes and 'grep' to filter for the keyword.

ps -aux | grep bash
