#!/usr/bin/env bash
# to_infinity_and_beyond.sh
# Description: Displays the message "To infinity and beyond" indefinitely
#              with a sleep of 2 seconds between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
done
