#!/usr/bin/env bash
# Configures an Ubuntu server to modify the IP addresses for localhost and facebook.com.

# Create a backup of the original hosts file
cp /etc/hosts ~/hosts.new

# Update the IP address for localhost in the new hosts file
echo "127.0.0.2		localhost" > ~/hosts.new

# Add a new entry for facebook.com with the desired IP address
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Replace the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
