#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Use ifconfig to retrieve network interface information,
# extract IPv4 addresses using grep and regular expressions,
# and remove unnecessary characters using cut.

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
