#!/usr/bin/env bash
# Fix Apache in Docker container to return "Hello Holberton"

# Step 2
docker exec -it <container_id> /bin/bash

# Step 3
apt-get update
apt-get install apache2 -y

# Step 4
echo "Hello Holberton" > /var/www/html/index.html

# Step 5
if service apache2 status | grep -q "apache2 is running"; then
    echo "Apache is running"
else
    service apache2 start
fi

#Step 6
exit
