#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user.

# Stop the existing Nginx service
service nginx stop

# Modify the Nginx configuration to run as the nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Start Nginx with the new configuration
service nginx start

# Check if Nginx is running as the nginx user
ps auxff | grep ngin[x]

# Check if Nginx is listening on port 8080
nc -z 0 8080
